//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasTrabajoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leasing
    {
        public int idLeasing { get; set; }
        public int idCarro { get; set; }
        public int idDNI { get; set; }
        public int idBanco { get; set; }
        public float NprevioVenta { get; set; }
        public float NcuotaInical { get; set; }
        public int NAnios { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public int idFrecuencia { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual carro carro { get; set; }
        public virtual Frecuencia Frecuencia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
